### ISSUE TITLE
bug: adunit: it's possible to try to create one without a type (results in a market error)

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-dapp#117]
results in a market error:

```
Error: TYPE_ERR_UNIT
    at Object.<anonymous> (/app/node_modules/adex-models/src/schemas.js:38:75)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/node_modules/adex-models/src/index.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
```

**Comment by IvoPaunov** [comment]
Fixed 9a2f7f95759b229c194d75fcd353edbb49a1dc77
